module.exports = {
  // gifs
  "ebete": { type: 'gif', id: 'CgADBAADUQEAAmwOuFBmTOzUIz9ElAI' },
  "gabice": { type: 'gif', id: 'CgADBAADHQEAAisxKFG403Uvb_7mbwI' },

  // stickerzzz
  "bravo": { type: 'sticker', id: 'CAADBAADHxEAAmpj7wTIWvUa0fLgpQI' },
  "brao": { type: 'sticker', id: 'CAADBAADHxEAAmpj7wTIWvUa0fLgpQI' },
  "orcodio": { type: 'sticker', id: 'CAADBAAD6hAAAmpj7wSzUKVLXpHwfgI' },
  "fesso": { type: 'sticker', id: 'CAADBAAD_RAAAmpj7wSeHyWXUsBM2wI' },
  "droghe": { type: 'sticker', id: 'CAADBAADChEAAmpj7wSnWSdk7jUybgI' },
  "salve": { type: 'sticker', id: 'CAADBAADHBEAAmpj7wTH0sQg' },
  "gne": { type: 'sticker', id: 'CAADBAADIREAAmpj7wS0vSdZB7ZkpgI' },
  "vorresti": { type: 'sticker', id: 'CAADBAADKxEAAmpj7wRvkBqGbtvIEwI' },
  "dannaz": { type: 'sticker', id: 'CAADBAAD-RAAAmpj7wQW8CEFONnCpwI' },
  "fregato": { type: 'sticker', id: 'CAADBAADBBEAAmpj7wT0vQtY1snCjAI' },
  "steso": { type: 'sticker', id: 'CAADBAADCREAAmpj7wQJOMnJ2sZPEgI' },
  "defunto": { type: 'sticker', id: 'CAADBAADFREAAmpj7wRmyI0Msbp-JgI' },
  "sparati": { type: 'sticker', id: 'CAADBAADLxEAAmpj7wTCRSc3MFDaXgI' },
  "ma taci": { type: 'sticker', id: 'CAADBAADGREAAmpj7wTjy5l9yBpdqAI' },
  "taci": { type: 'sticker', id: 'CAADBAADGREAAmpj7wTjy5l9yBpdqAI' },
  "certo": { type: 'sticker', id: 'CAADBAADGxEAAmpj7wTWHIcy2F2PHwI' },
  "furbo": { type: 'sticker', id: 'CAADBAADAREAAmpj7wS85LY5eKndaAI' },
  "offeso": { type: 'sticker', id: 'CAADBAAD-xAAAmpj7wQ7BXm_t7iHJgI' },
  "svea": { type: 'sticker', id: 'CAADBAAD_hAAAmpj7wS4xoO3Mcx-EQI' },

  "cinesi": { type: 'sticker', id: 'CAADBAADMxEAAmpj7wRez62CuapX1AI' },
  "bello": { type: 'sticker', id: 'CAADBAADMREAAmpj7wQ0l2x4wxgIQQI' },
  "che": { type: 'sticker', id: 'CAADBAADLREAAmpj7wTrHEoWckz1jgI' },
  "seh volevi": { type: 'sticker', id: 'CAADBAADMBEAAmpj7wR6T__4H1unQwI' },
  "pigliato": { type: 'sticker', id: 'CAADBAADKBEAAmpj7wTSNOaNz5kuJQI' },
  "a": { type: 'sticker', id: 'CAADBAADJhEAAmpj7wRFdEX8BVULpAI' },
  "l": { type: 'sticker', id: 'CAADBAADIxEAAmpj7wSTZnRcvLZq7gI' },
  "utile": { type: 'sticker', id: 'CAADBAADIBEAAmpj7wRGE_vHX42vggI' },
  "boh": { type: 'sticker', id: 'CAADBAADHhEAAmpj7wTJRdAhfOpYuAI' },
  "te movi": { type: 'sticker', id: 'CAADBAADHREAAmpj7wT-Ky1-sVCmrgI' },
  "se vedemo": { type: 'sticker', id: 'CAADBAADKhEAAmpj7wReSZ5pxMGKOgI' },
  "bugs": { type: 'sticker', id: 'CAADBAADGBEAAmpj7wQVeutrUjUe1QI' },
  "stop this": { type: 'sticker', id: 'CAADBAADEBEAAmpj7wT5g7R5oR-XuAI' },
  "e invece": { type: 'sticker', id: 'CAADBAADAxEAAmpj7wRY4UQf-J05JwI' },
  "cugliun": { type: 'sticker', id: 'CAADBAADDBEAAmpj7wR23AdActegTAI' },
  "o k": { type: 'sticker', id: 'CAADBAAD_BAAAmpj7wQAAUAi-et-2h0C' },
  "n o": { type: 'sticker', id: 'CAADBAADAhEAAmpj7wSBRgo3Cy_x2gI' },
  "errato": { type: 'sticker', id: 'CAADBAADDxEAAmpj7wSDX3jSS0FaVgI' },
  "falso": { type: 'sticker', id: 'CAADBAAD9xAAAmpj7wTxBcbQ3PN4OwI' },
  "ao": { type: 'sticker', id: 'CAADBAAD9RAAAmpj7wTsvxx1FJcCRgI' },
  "magnifico": { type: 'sticker', id: 'CAADBAAD8xAAAmpj7wSYh6Q9RG1iCQI' },
  "ritardo": { type: 'sticker', id: 'CAADBAAD8RAAAmpj7wR3geSo8ECzNAI' },
  "rapido": { type: 'sticker', id: 'CAADBAAD7BAAAmpj7wQe2Awa0Qb5jgI' },
  "folto": { type: 'sticker', id: 'CAADBAAD5hAAAmpj7wSVQUpwoj19agI' },
  "cristo ebete": { type: 'sticker', id: 'CAADBAAD6xAAAmpj7wTWQVF9p_o6cAI' },
  "madonna savana": { type: 'sticker', id: 'CAADBAADJxEAAmpj7wRj01Eav0yJnwI' },
  "porco dio": { type: 'sticker', id: 'CAADBAADMhEAAmpj7wT9Qq7XHg_jsQI' },
  "cristocane": { type: 'sticker', id: 'CAADBAADLhEAAmpj7wR7SNCLhIMFSgI' },
  "madonna lobster": { type: 'sticker', id: 'CAADBAAD6BAAAmpj7wSDfOxnAYqmrAI' },
  "dio the": { type: 'sticker', id: 'CAADBAAD9BAAAmpj7wTuxBD0BkZH4wI' },
  "madonna troia": { type: 'sticker', id: 'CAADBAAD5RAAAmpj7wRBM7SPgAONegI' },
  "porco": { type: 'sticker', id: 'CAADBAAD4xAAAmpj7wQG8WXcYUZ3iwI' },
}
