module.exports = {
  // gifs
  "ebete": { type: 'gif', id: 'CgADBAADUQEAAmwOuFBmTOzUIz9ElAI' },
  "gabice": { type: 'gif', id: 'CgADBAADHQEAAisxKFG403Uvb_7mbwI' },

  // stickers
  "node": { type: 'sticker', id: 'CAADBAADAQEAApdrhgSgTMtDyqWjVAI' },
  "certo": { type: 'sticker', id: 'CAADBAADGxEAAmpj7wTWHIcy2F2PHwI' },
  "porco": { type: 'sticker', id: 'CAADBAAD4xAAAmpj7wQG8WXcYUZ3iwI' },
  "madonna troia": { type: 'sticker', id: 'CAADBAAD5RAAAmpj7wRBM7SPgAONegI' },
  "dio the": { type: 'sticker', id: 'CAADBAAD9BAAAmpj7wTuxBD0BkZH4wI' },
  "madonna lobster": { type: 'sticker', id: 'CAADBAAD6BAAAmpj7wSDfOxnAYqmrAI' },
  "orcodio": { type: 'sticker', id: 'CAADBAAD6hAAAmpj7wSzUKVLXpHwfgI' },
  "cristocane": { type: 'sticker', id: 'CAADBAADLhEAAmpj7wR7SNCLhIMFSgI' },
  "porco dio": { type: 'sticker', id: 'CAADBAADMhEAAmpj7wT9Qq7XHg_jsQI' },
  "dio boia": { type: 'sticker', id: 'CAADBAADOBEAAmpj7wSIo9Z_qxuJGwI' },
  "dio maiale": { type: 'sticker', id: 'CAADBAADNREAAmpj7wQi-7RIf82x6gI' },
  "dio viscido": { type: 'sticker', id: 'CAADBAADSBEAAmpj7wStclGjjHrIUQI' },
  "dio sputo": { type: 'sticker', id: 'CAADBAADWREAAmpj7wRGVRgoQmI3LQI' },
  "dio cedro": { type: 'sticker', id: 'CAADBAADcBEAAmpj7wRbUFtZrmEkaQI' },
  "basta diocane": { type: 'sticker', id: 'CAADBAADZREAAmpj7wTpC2kxEZNbtQI' },
  "madonna savana": { type: 'sticker', id: 'CAADBAADJxEAAmpj7wRj01Eav0yJnwI' },
  "cristo ebete": { type: 'sticker', id: 'CAADBAAD6xAAAmpj7wTWQVF9p_o6cAI' },
  "folto": { type: 'sticker', id: 'CAADBAAD5hAAAmpj7wSVQUpwoj19agI' },
  "rapido": { type: 'sticker', id: 'CAADBAAD7BAAAmpj7wQe2Awa0Qb5jgI' },
  "tristezza": { type: 'sticker', id: 'CAADBAAD7RAAAmpj7wTMSjELDlrqagI' },
  "...": { type: 'sticker', id: 'CAADBAADTxEAAmpj7wQ4LREtDht6_QI' },
  "eh?": { type: 'sticker', id: 'CAADBAAD4BAAAmpj7wQpx0X7w5VnqwI' },
  "ritardo": { type: 'sticker', id: 'CAADBAAD8RAAAmpj7wR3geSo8ECzNAI' },
  "magnifico": { type: 'sticker', id: 'CAADBAAD8xAAAmpj7wSYh6Q9RG1iCQI' },
  "perfetto": { type: 'sticker', id: 'CAADBAADXxEAAmpj7wTo_WIvFYG4BwI' },
  "bona": { type: 'sticker', id: 'CAADBAADYBEAAmpj7wSEpb5RuEnGOwI' },
  "a o": { type: 'sticker', id: 'CAADBAAD9RAAAmpj7wTsvxx1FJcCRgI' },
  "falso": { type: 'sticker', id: 'CAADBAAD9xAAAmpj7wTxBcbQ3PN4OwI' },
  "errato": { type: 'sticker', id: 'CAADBAADDxEAAmpj7wSDX3jSS0FaVgI' },
  "dannaz": { type: 'sticker', id: 'CAADBAAD-RAAAmpj7wQW8CEFONnCpwI' },
  "n  o": { type: 'sticker', id: 'CAADBAAD-hAAAmpj7wTyv44CQAoC1AI' },
  "n o": { type: 'sticker', id: 'CAADBAADAhEAAmpj7wSBRgo3Cy_x2gI' },
  "offeso": { type: 'sticker', id: 'CAADBAAD-xAAAmpj7wQ7BXm_t7iHJgI' },
  "o k": { type: 'sticker', id: 'CAADBAAD_BAAAmpj7wQAAUAi-et-2h0C' },
  "fesso": { type: 'sticker', id: 'CAADBAAD_RAAAmpj7wSeHyWXUsBM2wI' },
  "cugliun": { type: 'sticker', id: 'CAADBAADDBEAAmpj7wR23AdActegTAI' },
  "svea": { type: 'sticker', id: 'CAADBAAD_hAAAmpj7wS4xoO3Mcx-EQI' },
  "ma taci": { type: 'sticker', id: 'CAADBAADGREAAmpj7wTjy5l9yBpdqAI' },
  "furbo": { type: 'sticker', id: 'CAADBAADAREAAmpj7wS85LY5eKndaAI' },
  "e invece": { type: 'sticker', id: 'CAADBAADAxEAAmpj7wRY4UQf-J05JwI' },
  "come no": { type: 'sticker', id: 'CAADBAADYREAAmpj7wQFX-oJ_bnXNwI' },
  "fregato": { type: 'sticker', id: 'CAADBAADBBEAAmpj7wT0vQtY1snCjAI' },
  "beccate questa": { type: 'sticker', id: 'CAADBAADThEAAmpj7wQzFtYhLzw9wAI' },
  "mitu": { type: 'sticker', id: 'CAADBAADBREAAmpj7wSuNQABMKCt99UC' },
  "mi tu": { type: 'sticker', id: 'CAADBAADBhEAAmpj7wQSw6_kpXfVbwI' },
  "steso": { type: 'sticker', id: 'CAADBAADCREAAmpj7wQJOMnJ2sZPEgI' },
  "defunto": { type: 'sticker', id: 'CAADBAADFREAAmpj7wRmyI0Msbp-JgI' },
  "ma va": { type: 'sticker', id: 'CAADBAADFBEAAmpj7wT-J3B7yGJNvAI' },
  "e h": { type: 'sticker', id: 'CAADBAADExEAAmpj7wTeaxt_JTxLJgI' },
  "droghe": { type: 'sticker', id: 'CAADBAADChEAAmpj7wSnWSdk7jUybgI' },
  "stop this": { type: 'sticker', id: 'CAADBAADEBEAAmpj7wT5g7R5oR-XuAI' },
  "m a": { type: 'sticker', id: 'CAADBAADGBEAAmpj7wQVeutrUjUe1QI' },
  "salve": { type: 'sticker', id: 'CAADBAADHBEAAmpj7wTH0sQg-bE2qAI' },
  "y o": { type: 'sticker', id: 'CAADBAADTBEAAmpj7wTS687Nk00CXwI' },
  "se vedemo": { type: 'sticker', id: 'CAADBAADKhEAAmpj7wReSZ5pxMGKOgI' },
  "te movi": { type: 'sticker', id: 'CAADBAADHREAAmpj7wT-Ky1-sVCmrgI' },
  "boh": { type: 'sticker', id: 'CAADBAADHhEAAmpj7wTJRdAhfOpYuAI' },
  "brao": { type: 'sticker', id: 'CAADBAADHxEAAmpj7wTIWvUa0fLgpQI' },
  "utile": { type: 'sticker', id: 'CAADBAADIBEAAmpj7wRGE_vHX42vggI' },
  "gne": { type: 'sticker', id: 'CAADBAADIREAAmpj7wS0vSdZB7ZkpgI' },
  "l": { type: 'sticker', id: 'CAADBAADIxEAAmpj7wSTZnRcvLZq7gI' },
  "a": { type: 'sticker', id: 'CAADBAADJhEAAmpj7wRFdEX8BVULpAI' },
  "pigliato": { type: 'sticker', id: 'CAADBAADKBEAAmpj7wTSNOaNz5kuJQI' },
  "vorresti": { type: 'sticker', id: 'CAADBAADKxEAAmpj7wRvkBqGbtvIEwI' },
  "seh volevi": { type: 'sticker', id: 'CAADBAADMBEAAmpj7wR6T__4H1unQwI' },
  "sparati": { type: 'sticker', id: 'CAADBAADLxEAAmpj7wTCRSc3MFDaXgI' },
  "che": { type: 'sticker', id: 'CAADBAADLREAAmpj7wTrHEoWckz1jgI' },
  "palese": { type: 'sticker', id: 'CAADBAADTREAAmpj7wT0j8chJLEIxgI' },
  "bello": { type: 'sticker', id: 'CAADBAADMREAAmpj7wQ0l2x4wxgIQQI' },
  "cinesi": { type: 'sticker', id: 'CAADBAADMxEAAmpj7wRez62CuapX1AI' },
  "sagra": { type: 'sticker', id: 'CAADBAADOREAAmpj7wQhTAEVjaF0EwI' },
  "sei un mongolo": { type: 'sticker', id: 'CAADBAADOhEAAmpj7wQ196EDttAt1gI' },
  "me ne frego": { type: 'sticker', id: 'CAADBAADOxEAAmpj7wRiV2IMgV2_VQI' },
  "ma sei tordo": { type: 'sticker', id: 'CAADBAADPBEAAmpj7wTFUjpZpMpoOQI' },
  "muso": { type: 'sticker', id: 'CAADBAADPREAAmpj7wSdCt5gkAE0lwI' },
  "noci": { type: 'sticker', id: 'CAADBAADPhEAAmpj7wQBhW37hL7sbAI' },
  "che poi": { type: 'sticker', id: 'CAADBAADVREAAmpj7wSDz9EKlLRanAI' },
  "seghe": { type: 'sticker', id: 'CAADBAADPxEAAmpj7wTqPtepNWPOXwI' },
  "baciame er culo": { type: 'sticker', id: 'CAADBAADQBEAAmpj7wR5IqWBZHSkcQI' },
  "suka": { type: 'sticker', id: 'CAADBAADSREAAmpj7wRCNlQnTlrEMwI' },
  "inculati": { type: 'sticker', id: 'CAADBAADVxEAAmpj7wTtCWlEaimp8wI' },
  "piango": { type: 'sticker', id: 'CAADBAADQREAAmpj7wRhD8CwgUzLSgI' },
  "saf": { type: 'sticker', id: 'CAADBAADShEAAmpj7wT_CYnghJch4wI' },
  "tantomeno": { type: 'sticker', id: 'CAADBAADUBEAAmpj7wSScD-03GAfowI' },
  "quindi": { type: 'sticker', id: 'CAADBAADVhEAAmpj7wSe2ZG6jy5vlQI' },
  "mistico": { type: 'sticker', id: 'CAADBAADWBEAAmpj7wTCrN06geK29AI' },
  "salato": { type: 'sticker', id: 'CAADBAADWhEAAmpj7wRpdGse6o_FPwI' },
  "sti cazzi": { type: 'sticker', id: 'CAADBAADXhEAAmpj7wQDlzPLv3j92wI' },
  "sticazzi": { type: 'sticker', id: 'CAADBAADXhEAAmpj7wQDlzPLv3j92wI' },
  "no sense": { type: 'sticker', id: 'CAADBAADYhEAAmpj7wQ_PPDsEcYKvAI' },
  "gonzo": { type: 'sticker', id: 'CAADBAADYxEAAmpj7wQWNjybT29XcwI' },
  "c'eri quasi": { type: 'sticker', id: 'CAADBAADZBEAAmpj7wQVMnSlJrwqKwI' },
  "scoppia": { type: 'sticker', id: 'CAADBAADZhEAAmpj7wQ8c3Csrw8bWgI' },
  "sforzi": { type: 'sticker', id: 'CAADBAADZxEAAmpj7wQIbt_GUE1ciQI' },
  "diretto nell'ano": { type: 'sticker', id: 'CAADBAADaBEAAmpj7wTehBSgtxCy3gI' },
  "certo che": { type: 'sticker', id: 'CAADBAADaREAAmpj7wT4bZsQjIgeLAI' },
  "che palle": { type: 'sticker', id: 'CAADBAADahEAAmpj7wTpXvapvYnJEQI' },
  "go sonno": { type: 'sticker', id: 'CAADBAADaxEAAmpj7wQ7GJxWxokxlAI' },
  "sta calmo": { type: 'sticker', id: 'CAADBAADbBEAAmpj7wRoMxhC6bHuogI' },
  "passo": { type: 'sticker', id: 'CAADBAADbREAAmpj7wSuqid1Wut5mgI' },
  "ti legno": { type: 'sticker', id: 'CAADBAADbhEAAmpj7wQFFqIBPHBLygI' },
  "ma crepa": { type: 'sticker', id: 'CAADBAADbxEAAmpj7wT0I37Ra9ddEwI' },
  "ritirati": { type: 'sticker', id: 'CAADBAADchEAAmpj7wRqRWd67ThfmQI' },
  "n'culat": { type: 'sticker', id: 'CAADBAADcxEAAmpj7wSbm3GS3Kyr6gI' },
  "tachete": { type: 'sticker', id: 'CAADBAADdBEAAmpj7wTZhufaBwZZPwI' },
  "seh ciao": { type: 'sticker', id: 'CAADBAADdREAAmpj7wSVOsPbQ5cnNwI' },
  "largo": { type: 'sticker', id: 'CAADBAADdhEAAmpj7wT7fa-4W7pvYAI' },
}